[package]
name = "alignment_check"
version = "0.1.0"
edition = "2021"

[dependencies]
svg2gcode = { path = "../../lib" }
roxmltree = { workspace = true }
svgtypes = { workspace = true }
g-code = { workspace = true }
