name: Publish svg2gcode-wasm to npm

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run (yes/no)'
        required: false
        default: 'yes'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install wasm-pack
        run: cargo install wasm-pack --locked

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: Derive version & dry-run mode
        id: derive
        working-directory: crates/svg2gcode-wasm
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            TAG="${GITHUB_REF_NAME}" # e.g. v0.1.1 or v0.1.1-test
            VERSION="${TAG#v}"
            echo "Detected tag version: $VERSION"
            npm pkg set version=$VERSION
            # propagate version into built pkg after build as well
            echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV
            # Treat tags ending with -test or -rc* as dry-run
            if [[ "$VERSION" == *-test || "$VERSION" == *-rc* ]]; then
              echo "DRY_RUN=true" >> $GITHUB_ENV
            fi
          fi
          # workflow_dispatch input overrides
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ inputs.dry_run }}" == "yes" ]]; then
            echo "DRY_RUN=true" >> $GITHUB_ENV
          fi
          : "Default to DRY_RUN false if not set"
          echo DRY_RUN=${DRY_RUN:-false}

      - name: Build wasm package
        working-directory: crates/svg2gcode-wasm
        run: npm run build:wasm

      - name: Verify build artifacts present
        working-directory: crates/svg2gcode-wasm
        run: |
          ls -al pkg
          test -f pkg/svg2gcode_wasm_bg.wasm || { echo 'WASM file missing'; exit 1; }
          size=$(stat -c%s pkg/svg2gcode_wasm_bg.wasm 2>/dev/null || wc -c < pkg/svg2gcode_wasm_bg.wasm)
            
          if [ "$size" -lt 10000 ]; then
            echo "Unexpectedly small wasm file ($size bytes)"; exit 1; fi
          echo "WASM size OK: $size bytes"
          # Pre-pack preview
          (cd pkg && npm pack --dry-run)

      - name: Pack (validation)
        working-directory: crates/svg2gcode-wasm
        run: |
          npm pack --dry-run
          ls -lh *.tgz || true

      - name: Sync version & metadata into pkg
        if: env.PACKAGE_VERSION != ''
        working-directory: crates/svg2gcode-wasm
        run: |
          node -e "const fs=require('fs');const p=JSON.parse(fs.readFileSync('pkg/package.json','utf8'));p.version=process.env.PACKAGE_VERSION; p.repository={type:'git', url:'git+https://github.com/tiagomelobr/svg2gcode.git'}; p.license='MIT'; fs.writeFileSync('pkg/package.json', JSON.stringify(p,null,2));"
          echo "pkg/package.json version set to $PACKAGE_VERSION"

      - name: Publish (or dry-run) from pkg directory
        if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
        working-directory: crates/svg2gcode-wasm/pkg
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "About to publish from $(pwd)"
          ls -al
          if [ "$DRY_RUN" = "true" ]; then
            echo "Running npm publish --dry-run (no artifacts will be released)";
            npm publish --access public --dry-run;
          else
            echo "Publishing to npm (pkg directory contents)";
            npm publish --access public;
          fi

      - name: Upload packaged artifact
        uses: actions/upload-artifact@v4
        with:
          name: svg2gcode-wasm-pkg
          path: |
            crates/svg2gcode-wasm/pkg
            crates/svg2gcode-wasm/pkg/*.tgz
